### ISSUE TITLE
master已经加了GetClient方法

### ISSUE THREAD

**Issue by a5635268** [matchstalk/go-admin-core#2]
master已经加了GetClient方法

_Originally posted by @lwnmengjing in https://github.com/matchstalk/go-admin-core/issues/1#issuecomment-698830444_

只改此处地方应该会报错，上面还有接口约束方法的

**Comment by a5635268** [comment]
应该还要改一下`type Adapter interface`

**Comment by lwnmengjing** [comment]
你可以直接使用这边的redis，不使用go-admin那边封装的interface

**Comment by a5635268** [comment]
> 
> 
> 你可以直接使用这边的redis，不使用go-admin那边封装的interface

嗯嗯，好的
